version: '3'

services:
  app:
    build: .
    container_name: deploy-maven-app
    restart: on-failure

  nginx:
    image: nginx:mainline
    container_name: deploy-maven-nginx
    ports:
      - "80:80"
    volumes:
      - ./deploy-maven.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: on-failure
